apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-wrapper-pv
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /srv/nfs/kubedata/llm-wrapper
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
